export type Team = { id: string; name: string; short: string; color: string; seed: number; region: string; logoUrl?: string }
export type Role = 'carry' | 'mid' | 'offlane' | 'support' | 'hard-support'
export type Player = { id: string; name: string; realName?: string; teamId: string; role: Role; country: string; rating: number }
export type Hero = { id: string; name: string; nameEs: string; attribute: 'str' | 'agi' | 'int' | 'uni'; roles: string[]; iconUrl?: string }
export type DraftAction = { type: 'pick' | 'ban'; side: 'radiant' | 'dire'; heroId: string; order: number; playerId?: string }
export type PlayerStats = { playerId: string; heroId: string; kills: number; deaths: number; assists: number; netWorth: number; gpm: number; xpm: number; lastHits: number; denies: number; level: number; itemIds: string[] }
export type EconomyPoint = { minute: number; radiantNW: number; direNW: number; radiantXP: number; direXP: number }
export type WinProbPoint = { minute: number; radiant: number; dire: number }
export type MatchStatus = 'live' | 'upcoming' | 'finished' | 'cancelled'
export type GameEvent = { minute: string; type: 'kill' | 'tower' | 'roshan' | 'building' | 'teamfight' | 'item'; text: string; detail: string }
export type GameDetail = { gameNumber: number; duration: string; radiantScore: number; direScore: number; winner?: 'radiant' | 'dire'; winProbHistory: WinProbPoint[]; economyHistory: EconomyPoint[]; draft: DraftAction[]; playerStats: PlayerStats[]; events: GameEvent[] }
export type Match = { id: string; radiant: Team; dire: Team; radiantScore: number; direScore: number; status: MatchStatus; phase: string; format: 'BO1' | 'BO2' | 'BO3' | 'BO5'; scheduledAt: string; currentGame?: number; games: GameDetail[]; liveGame?: GameDetail }
export type BracketSlot = { id: string; phase: string; format: string; teamA?: Team; teamB?: Team; scoreA: number; scoreB: number; status: MatchStatus; matchId?: string }
export type PanchoRecommendation = { id: string; matchId?: string; tag: string; title: string; body: string; winPct?: number; heroToWatch?: string; upsetAlert: boolean; createdAt: string }
export type Post = { id: string; userId: string; username: string; avatar: string; room: string; text: string; likes: number; replies: number; createdAt: string }
export type ChatMessage = { id: string; userId: string; username: string; text: string; timestamp: string; reactions?: Record<string, number> }
export type Prediction = { id: string; userId: string; matchId: string; predictedWinner: string; predictedScore: string; locked: boolean; correct?: boolean }
export type DataSource = 'MOCK' | 'LIVE' | 'OFFICIAL' | 'SIMULATION'
export type DataStatus = { source: DataSource; label: string; lastUpdated: string; connected: boolean }
